// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFMRe8v9ktSGFGYu_DOpZE_NOhMIZh2Cw',
    appId: '1:942478086379:android:4da50b2c5ba37b23cf2eae',
    messagingSenderId: '942478086379',
    projectId: 'applications-7f5d0',
    databaseURL: 'https://applications-7f5d0-default-rtdb.firebaseio.com',
    storageBucket: 'applications-7f5d0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxvlPCYizopt0HwnB14wz1kZqvFk-6dgQ',
    appId: '1:942478086379:ios:5e0d99a5f6ae5eb3cf2eae',
    messagingSenderId: '942478086379',
    projectId: 'applications-7f5d0',
    databaseURL: 'https://applications-7f5d0-default-rtdb.firebaseio.com',
    storageBucket: 'applications-7f5d0.firebasestorage.app',
    iosBundleId: 'com.example.fantasyCricketApp',
  );
}
